version: "3"
services:
  backend:
    image: ${DOCKER_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD
    env_file:
      - .env
=======
    container_name: ${DOCKER_CONTAINER_NAME}
>>>>>>> 179f9f31a656b3f31deff1084757a3e9c8cc5896
    ports:
      - "8000:8000"
    environment:
      - QDRANT_API_URL=${QDRANT_API_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_URL=${APP_URL}
