from app.environment import get_env_var

PASSWORD_SECRET_KEY = get_env_var("PASSWORD_SECRET_KEY")
PASSWORD_HASHING_ALGORITHM = get_env_var("PASSWORD_HASHING_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = get_env_var("ACCESS_TOKEN_EXPIRE_MINUTES")
