name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}
      env:
        region: ${{ secrets.AWS_REGION }}

    - name: Build and push Docker image to ECR
      run: |
        docker build -t rag-api .
        docker tag rag-api:latest 584448014764.dkr.ecr.us-east-2.amazonaws.com/rag-api:latest
        docker push 584448014764.dkr.ecr.us-east-2.amazonaws.com/rag-api:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        QDRANT_API_URL: ${{ secrets.QDRANT_API_URL }}
        QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          docker pull 584448014764.dkr.ecr.us-east-2.amazonaws.com/rag-api:latest
          docker stop rag-api || true
          docker rm rag-api || true
          docker run -d -p 80:8000 --name rag-api 584448014764.dkr.ecr.us-east-2.amazonaws.com/rag-api:latest
